#!/bin/bash

set -o nounset
set -o errexit

if ! git diff --exit-code TrackAnalyzer.cxx; then
  echo "error! uncommitted changes to TrackAnalyzer.cxx, will not run over all 100 million"
  exit 1
fi

commit_sha="$(git rev-parse --short=8 HEAD)"
denv fire track_ana_cfg.py \
  --run-tag "${commit_sha}" \
  /local/cms/user/eichl008/ldmx/eat/v14/8gev/bkgd/inclusive-no-cal-0/category_inclusivenocals_beam_8gev_nevents_1M_run_01* |\
  tee "100-mill-events-${commit_sha}.log"
